### ISSUE TITLE
NotReadableError: Could not start video source

### ISSUE THREAD

**Issue by oleteacher** [defeo/castaphone#1]
Greetings! Looking for something like this to use in classroom.

Trying to demo (using yours online) but cannot get it to work.

Allowed access to mic / cam:
![image](https://user-images.githubusercontent.com/26278259/77255578-914d0880-6c36-11ea-9bfd-1c75cb4d20ac.png)

I press "Launch Castaphone" on webpage:
![image](https://user-images.githubusercontent.com/26278259/77255583-9a3dda00-6c36-11ea-88dd-c456a4ed3180.png)

There are no errors shown in dev console.

Any ideas what issue might be?

Thanks much!

**Comment by oleteacher** [comment]
I just found solution after little tip. Windows 10 has privacy setting for camera:

Go to Start  > Settings  > Privacy  > Camera.

Was not allowed for my browser.

Thanks for sharing your app!

**Comment by defeo** [comment]
Thanks! I'll add that to the FAQ.
